src/ScriptCs/Command/FileWatcher.cs
The defect https://scan8.coverity.com:8443/reports.htm#v21582/p10801/fileInstanceId=3240428&defectInstanceId=1396798&mergedDefectId=96018 found by Coverity is actually a false positive since the locking was not in place to give public thread safety but only to guarantee correct implementation, given the internal timer thread, but reading the code, it was difficult to tell. I considered suppressing the warning but then I realised making the type threadsafe was actually a trivial change and removes ambiguity for the reader so I thought to go down that route instead.
=> made FileWatcher threadsafe

src/ScriptCs.Hosting/ModuleLoader.cs, src/ScriptCs.Hosting/Properties/AssemblyInfo.cs, src/ScriptCs.Hosting/ScriptServicesBuilder.cs, test/ScriptCs.Hosting.Tests/ModuleLoaderTests.cs
Fixes #964 
Great perf benefit - improves startup from ~1.5s to ~0.5s.
Tested on Win and OS X
=> Do not use initialize modules MEF catalog if the only module in play is Roslyn or Mono

build/ScriptCs.Version.props
fixes #978 
Also has a nice side effect:
Previously, only `0.14.0` would be shown here.
=> fix nightly package dependencies

src/ScriptCs.Hosting/ModuleLoader.cs, test/ScriptCs.Hosting.Tests/ModuleLoaderTests.cs
Fixes #964 and unblocks 0.14 release
The fast path is only invoked if there is:
- no explicit module provided AND
- file extension is "csx" OR no extension (REPL mode)
=> Only use fast path when extension is CSX or none

build/ScriptCs.Version.props
re #947
We need to start doing this immediately after each release, otherwise it's impossible for a consuming project which is currently using our 0.14 NuGet packages to update to our nightly NuGet packages.
=> change version from 0.14 to 0.15

src/ScriptCs.Core/PackageAssemblyResolver.cs, test/ScriptCs.Core.Tests/PackageAssemblyResolverTests.cs
noticed when implementing https://github.com/scriptcs/scriptcs/issues/847
=> change PackageAssemblyResolver to warn when packages directory does not exist

src/ScriptCs.Core/UsingLineProcessor.cs, test/ScriptCs.Core.Tests/UsingLineProcessorTests.cs
Currently we don't allow namespace aliasing - this PR fixes it.
Fixes #826
=> Support for namespace aliasing

src/ScriptCs.Contracts/ScriptPackSession.cs, src/ScriptCs.Core/Extensions/EnumerableExtensions.cs, src/ScriptCs.Core/Extensions/MethodInfoExtensions.cs, src/ScriptCs.Core/Extensions/TypeExtensions.cs, src/ScriptCs.Core/ReplCommands/ScriptPacksCommand.cs, src/ScriptCs.Core/ScriptCs.Core.csproj, src/ScriptCs/ScriptCs.csproj, test/ScriptCs.Core.Tests/ReplCommands/ScriptPacksCommandTests.cs, test/ScriptCs.Core.Tests/ScriptCs.Core.Tests.csproj
Allows to easily inspect the script packs available in the REPL context.
- prints method signatures (including extension methods)
- prints property definitions (including correct getter/setter)
- uses fully qualified type names if the given namespace is not imported into REPL context, if it is imported uses simple type name
Example:
=> Added :scriptpacks REPL command

src/ScriptCs.Core/AppDomainAssemblyResolver.cs
Hello,  I thought you might like to add null checks to the arguments of this constructor.
FYI, I found these missing checks with a static analysis tool I'm working on based on CodeContracts and Roslyn.  I can run it over the whole repo and provide the full output if you're interested.  If you're interested in running the tool yourself, it is open source and on github.  I'll be making the repo public soon. Thanks!
=> Add null checks to AppDomainAssemblyResolver constructor

src/ScriptCs.Core/FilePreProcessor.cs, src/ScriptCs.Core/LoadLineProcessor.cs, src/ScriptCs.Core/ReferenceLineProcessor.cs, src/ScriptCs.Core/ReplCommands/AliasCommand.cs, src/ScriptCs.Core/ReplCommands/ExitCommand.cs, src/ScriptCs.Core/ReplCommands/HelpCommand.cs
Hi, these are some more missing null checks my static analyzer found.
Note: the analyzer didn't suggest a null check for lineProcessors in FilePreProcessor.  I'm not sure why.  I can add it if you want.
=> Add missing null checks found by static analysis

src/ScriptCs.Hosting/ScriptServicesBuilder.cs, test/ScriptCs.Hosting.Tests/ScriptServicesBuilderTests.cs
I noticed that most of the fluent methods for `ScriptServicesBuilder` didn't have unit tests.
If you prefer for this to have them, just say so. :kissing_cat:
=> convenience method on ScriptServicesBuilder

src/ScriptCs.Core/Repl.cs, src/ScriptCs.Core/ScriptExecutorExtensions.cs
This is rest I could find except one (potentially).
When I was looking [here](https://github.com/scriptcs/scriptcs/blob/dev/src/ScriptCs.Core/Repl.cs#29) I thought it was weird that the tool didn't suggest a null check for _scriptArgs.  I don't know why exactly, but I believe it has something to do with the parameter scriptEngine being an interface type.  scriptArgs only ever gets passed as the second argument to ScriptEngine.Execute.  Since IScriptEngine is a public interface I can't know all the possible implementations of it, right?  So I can't know if the implementer will just dereference the null parameter or check for it.
I looked through the code for the implementers of IScriptEngine and its only inherited by another interface (IReplEngine).  IReplEngine is only implemented by …
=> Add rest of the missing null checks (that I could find)

src/ScriptCs.Engine.Mono/app.config, src/ScriptCs.Hosting/ScriptCs.Hosting.csproj, src/ScriptCs.Hosting/packages.config, test/ScriptCs.Core.Tests/ScriptCs.Core.Tests.csproj, test/ScriptCs.Core.Tests/packages.config, test/ScriptCs.Hosting.Tests/ScriptCs.Hosting.Tests.csproj, test/ScriptCs.Hosting.Tests/packages.config
NuGet.Core was renamed to Nuget.Core recently.
Since we reference "NuGet.Core" it is impossible to install scriptcs packages using KPM because KPM is currently case sensitive.
@scriptcs/core this should be merged and shipped ASAP as it's preventing anyone to use scriptcs.hosting in ASP.NET 5
=> updated to Nuget.Core 2.8.5 and renamed "NuGet.Core" to "Nuget.Core"

src/ScriptCs.Core/Repl.cs, src/ScriptCs.Core/ScriptExecutor.cs, test/ScriptCs.Core.Tests/ReplTests.cs, test/ScriptCs.Core.Tests/ScriptExecutorTests.cs
Refactoring a new `ScriptExecutor.EngineExecute` method and fixing logic in Executor and Repl to propagate references and imports for Script Libraries
Fix for #1025 and #1026
=> Refactoring ScriptExecutor and fixing logic

src/ScriptCs.Engine.Mono/MonoScriptEngine.cs
fixes #847 - see https://github.com/scriptcs/scriptcs/issues/847#issuecomment-126005509
=> restore deprecated Common.Logging.ILog MonoScriptEngine.Logger

src/ScriptCs.Hosting/ScriptCs.Hosting.csproj, src/ScriptCs.Hosting/packages.config, test/ScriptCs.Core.Tests/ScriptCs.Core.Tests.csproj, test/ScriptCs.Core.Tests/packages.config, test/ScriptCs.Hosting.Tests/ScriptCs.Hosting.Tests.csproj, test/ScriptCs.Hosting.Tests/packages.config
Do you have any issues with upgrading nuget to version 2.8.6?
I'm unable to restore the current 2.8.5 nuget package with my linux/monodevelop setup!
I suspect there might be some cross-platform issues with that version.
=> Upgrade to NuGet 2.8.6

README.md
While the current usage of the `cinst` and `cup` aliases continue to work, Chocolatey is moving towards the ubiquitous usage of the `choco` command.  As a result, the new guidance for installing/updating packages is:
`choco install <packagename>`
`choco upgrade <packagename>`
As you can see [here](https://chocolatey.org/packages/ScriptCs).
So I thought I would update the installation/upgrade instructions contained on your readme.md.
=> (docs) Removing usage of Chocolatey aliases

README.md
Happened to notice a missing parenthesis around the name of one of the core committer, so thought I would correct it while I was here :smile:
=> (docs) Added missing opening parenthesis

src/ScriptCs.Hosting/Package/PackageObject.cs
This fixes #1053 temporarily until NuGet fixes this.
Because the files are not used in any manner (at least I have not found any) they can safely be removed.
=> Added a hotfix which deletes temporary folders created by NuGet

src/ScriptCs/Properties/chocolateyInstall.ps1, src/ScriptCs/Properties/scriptcs.nuspec
Previous versions required that Roslyn be restored from NuGet. This is no longer necessary, since we now distribute a more recent release of Roslyn in our package.
Steps to test:
1. Run `build.cmd`.
2. Navigate to `artifacts\Release`.
3. Run `choco install scriptcs -source .`
Scriptcs v0.16.0 should install without error.
=> ChocolateyInstall.ps1 should not restore Roslyn packages

src/ScriptCs.Engine.Roslyn/CSharpPersistentEngine.cs
there is some change in the Roslyn behavior in 1.0.0
Fixes #1153
=> load assembly into AppDomain in CSharpPersistentEngine

src/ScriptCs.Contracts/IScriptEnvironment.cs, src/ScriptCs.Contracts/Printers.cs, src/ScriptCs.Contracts/ScriptCs.Contracts.csproj, src/ScriptCs.Core/Repl.cs, src/ScriptCs.Core/ScriptEnvironment.cs, src/ScriptCs.Core/ScriptHost.cs, src/ScriptCs.Core/ScriptHostFactory.cs, src/ScriptCs.Hosting/RuntimeServices.cs, test/ScriptCs.Core.Tests/ReplCommands/AliasCommandTests.cs, test/ScriptCs.Core.Tests/ReplTests.cs, test/ScriptCs.Core.Tests/ScriptHostTests.cs, test/ScriptCs.Engine.Mono.Tests/MonoScriptEngineTests.cs, test/ScriptCs.Engine.Roslyn.Tests/CSharpScriptEngineTests.cs, test/ScriptCs.Engine.Roslyn.Tests/CSharpScriptInMemoryEngineTests.cs
Pretty printing support for ScriptCS in REPL
(some of original changes are squashed in @glennblock commit)
```code
$ scriptcs
scriptcs (ctrl-c to exit or :help for help)
> Env.AddCustomPrinter<int>(x => "testing " + x)
Adding custom printer for Int32
> 5
testing 5
>  
```
For running scripts without repl you can also use:
> Env.Print(25)
testing 25
There is also an overload for Print< T >(T obj) that allows for Print<Base>(derived)
@glennblock and I were also discussing the possibility of extracting a Printers interface (a little odd in a test setup to pass the dependecy in).
As state before this is to open up conversation.
=> Pretty Printing

src/ScriptCs.Hosting/Package/NugetInstallationProvider.cs
Fix for #1018 that sets the global credential provider. This allows the NuGet HttpClient to use the credentials stored in NuGet.Config .
I tested this by editing my `%APPDATA%\NuGet\NuGet.Config` file to use `packageSourceCredentials` for our myget feeds, specifically our nuget mirror. This file has Username and Password credentials for some of the MyGet feeds and nuget.org is disabled using:
```xml
<disabledPackageSources>
<add key="https://www.nuget.org/api/v2/" value="true" />
</disabledPackageSources>
```
I produced two builds using `build.cmd`, one from before the change and one from after and watched what they did using Fiddler. The build before the change would try the various feeds once and get a 401 response for each then just give up. The build after the change would retry with …
=> Set the global credential provider #1018

src/ScriptCs/Command/CommandFactory.cs, src/ScriptCs/Command/ExecuteLooseScriptCommand.cs, src/ScriptCs/Command/ICommand.cs, src/ScriptCs/Config.cs, src/ScriptCs/ConfigMask.cs, src/ScriptCs/ExecuteScriptCommandBase.cs, src/ScriptCs/ScriptCs.csproj, src/ScriptCs/ScriptCsArgs.cs, test/ScriptCs.Tests.Acceptance/LooseScriptExecution.cs, test/ScriptCs.Tests.Acceptance/ScriptCs.Tests.Acceptance.csproj, test/ScriptCs.Tests.Acceptance/Support/ScriptCsExe.cs, test/ScriptCs.Tests/CommandFactoryTests.cs, test/ScriptCs.Tests/ExecuteLooseScriptCommandTests.cs, test/ScriptCs.Tests/ScriptCs.Tests.csproj
This fixes #1085 
Update: _`-e` was chosen to align with the existing *nix precedent. Mono's REPL uses this and node as well. Thanks to @migueldeicaza for the suggestion!_
It adds a new switch for immediately executing loose code. Also adds a new convenience overload to the `ScriptCsExe.Run()` method.
example:
```
scriptcs -e 'Console.WriteLine("""Hello from scriptcs""");'
```
_Note_: Depending on the shell you use you may have to jump through different hoops for passing spaces / quoted strings. The example is using Powershell. To do this from the cmd prompt you would use:
```
scriptcs -e 'Console.WriteLine(\"\"\"Hello from scriptcs\"\"\");'
```
=> Adds new -e and --eval options which will immediately execute a script

src/ScriptCs.Engine.Mono/Segmenter/Lexer/ScriptLexer.cs, test/ScriptCs.Engine.Mono.Tests/Segmenter/ScriptLexerTests.cs
See #1143. The single quoted literal (char literal) does not work when there is more than one literal char in the string, which could be true if there are escape sequences involved.
I copied the code from the double quoted literal (string literal) token and this resolves the issue I was seeing. I had to change the code slightly to make the ShouldNotFailOnIdentifyingCharactersAsToken test succeed, as it seems the lexer needs to support some broken input (I am not sure I captured the real intent of the test though).
I added a unit test to ScriptLexerTests to show the case. It should fail without the fix and succeed with the fix
=> #1143. Char literals does not take escape sequences into account

src/ScriptCs.Contracts/FileParserContext.cs, src/ScriptCs.Contracts/FilePreProcessorResult.cs, src/ScriptCs.Contracts/IScriptEnvironment.cs, src/ScriptCs.Contracts/IScriptInfo.cs, src/ScriptCs.Contracts/ScriptCs.Contracts.csproj, src/ScriptCs.Core/DebugScriptExecutor.cs, src/ScriptCs.Core/FilePreProcessor.cs, src/ScriptCs.Core/Repl.cs, src/ScriptCs.Core/ScriptCs.Core.csproj, src/ScriptCs.Core/ScriptEnvironment.cs, src/ScriptCs.Core/ScriptExecutor.cs, src/ScriptCs.Core/ScriptHostFactory.cs, src/ScriptCs.Core/ScriptInfo.cs, src/ScriptCs.Hosting/RuntimeServices.cs, test/ScriptCs.Core.Tests/ReplCommands/AliasCommandTests.cs, test/ScriptCs.Core.Tests/ReplTests.cs, test/ScriptCs.Core.Tests/ScriptExecutorTests.cs, test/ScriptCs.Engine.Roslyn.Tests/CSharpScriptInMemoryEngineTests.cs
Fix for #225 
Creating this PR so others can review the approach.
This adds a new ScriptInfo class that is set with the path of the file that is executed. Ultimately the path is exposed off of the ambient `Env` property. The approach minimizes signature changes as it depends on ctor injection to get the ScriptInfo class passed around.
@scriptcs/core @rossipedia appreciate your thoughts.
Yes this issue is 2 1/2 years old.....
=> Adding ScriptPath to Env

src/ScriptCs.Contracts/IScriptEnvironment.cs, src/ScriptCs.Core/ScriptEnvironment.cs, src/ScriptCs.Core/ScriptInfo.cs, test/ScriptCs.Tests.Acceptance/ScriptExecution.cs
This feature adds a new `Env.ScriptAssembly` and fixes #244. The assembly is accessible in scripts or in the REPL.
=> Adding Env.ScriptAssembly
