scriptcs/scriptcs

src/ScriptCs.Hosting/Package/PackageInstaller.cs

My attention was drawn to this class by https://scan8.coverity.com:8443/reports.htm#v21582/p10801/fileInstanceId=3240400&defectInstanceId=1396801&mergedDefectId=96016
It's a false positive, but I spotted some low hanging fruit for refactoring, plus a couple of missing guard clauses.

Refactor PackageInstaller: add guard clauses and replace conditional with Where()

---

src/ScriptCs/Argument/ArgumentHandler.cs
src/ScriptCs/Argument/ArgumentParser.cs
test/ScriptCs.Tests/ArgumentParserTests.cs

Addresses https://scan8.coverity.com:8443/reports.htm#v21582/p10801/fileInstanceId=3240414&defectInstanceId=1396800&mergedDefectId=96015

Ensure ArgumentParser does not return null args

---

src/ScriptCs/Command/CommandFactory.cs
src/ScriptCs/Command/ExecuteReplCommand.cs
src/ScriptCs/Command/ICommand.cs
test/ScriptCs.Tests/CommandFactoryTests.cs

changed command line to assume REPL when no command or script name is passed

---

src/ScriptCs.Contracts/IFileSystem.cs
src/ScriptCs.Core/FileSystem.cs
src/ScriptCs/Command/CommandFactory.cs
src/ScriptCs/Command/ICommand.cs
src/ScriptCs/Command/MigrateCommand.cs
src/ScriptCs/ScriptCs.csproj
src/ScriptCs/ScriptCsArgs.cs
test/ScriptCs.Hosting.Tests/RuntimeServicesTests.cs
test/ScriptCs.Tests.Acceptance/Migration.cs
test/ScriptCs.Tests.Acceptance/ScriptCs.Tests.Acceptance.csproj
test/ScriptCs.Tests.Acceptance/ScriptExecution.cs
test/ScriptCs.Tests.Acceptance/ScriptPacks.cs
test/ScriptCs.Tests.Acceptance/Support/ScriptDirectory.cs
test/ScriptCs.Tests.Acceptance/Support/ScriptFile.cs
test/ScriptCs.Tests/CommandFactoryTests.cs

prefixed FileSystem locations with scriptcs_

---

src/ScriptCs/Argument/ArgumentParser.cs
src/ScriptCs/Program.cs
test/ScriptCs.Tests.Acceptance/CommandLine.cs
test/ScriptCs.Tests.Acceptance/ScriptCs.Tests.Acceptance.csproj
test/ScriptCs.Tests.Acceptance/ScriptExecution.cs
test/ScriptCs.Tests.Acceptance/ScriptPacks.cs
test/ScriptCs.Tests.Acceptance/Support/ScriptCsExe.cs
test/ScriptCs.Tests.Acceptance/Support/ScriptDirectory.cs
test/ScriptCs.Tests/ArgumentHandlerTests.cs
test/ScriptCs.Tests/ArgumentParserTests.cs

fixes #869 
needs to be merged before we can release 0.13 - see https://github.com/scriptcs/scriptcs/issues/869#issuecomment-69059235

implemented CommandLine.UnexpectedOption

---

build/ScriptCs.Version.props

increment to version 0.13.0

---

ScriptCs.sln.DotSettings
src/ScriptCs.Contracts/IAppDomainAssemblyResolver.cs
src/ScriptCs.Core/AppDomainAssemblyResolver.cs
src/ScriptCs.Core/AssemblyResolver.cs
src/ScriptCs.Hosting/ModuleLoader.cs
test/ScriptCs.Core.Tests/AssemblyResolverTests.cs

re #914
internalised/privatised implementation details
expanded parameter types
converted simple delegates to expressions
converted conditionals to LINQ calls
converted for..each list add to AddRange()
removed redundant code
whitespace fixes
added R# settings

refactorings from active code review of PR 914

---

src/ScriptCs.Hosting/ObjectSerializer.cs
test/ScriptCs.Hosting.Tests/ObjectSerializerTests.cs

fix for 700: changed ObjectSerializer to remove $id and $ref unless there is a circular ref

---

src/ScriptCs.Core/AssemblyUtility.cs
test/ScriptCs.Core.Tests/AssemblyUtilityTests.cs
test/ScriptCs.Core.Tests/ScriptCs.Core.Tests.csproj

Ensuring GAC dlls are loaded. Fix for #922

---

build/ScriptCs.Version.props
src/ScriptCs/Properties/chocolateyInstall.ps1

fix install script for choco < v0.9.8.33

---

build.sh

fixes #785
includes https://github.com/scriptcs/scriptcs/pull/824

Copy binaries to artifacts folder in build.sh #785

---

build/ScriptCs.Version.props

bump version number to 0.14.0

---

src/ScriptCs.Contracts/IScriptLibraryComposer.cs
src/ScriptCs.Core/NullScriptLibraryComposer.cs
src/ScriptCs.Core/ScriptCs.Core.csproj
src/ScriptCs.Core/ScriptExecutor.cs
src/ScriptCs.Core/ScriptLibraryComposer.cs
src/ScriptCs/Command/InstallCommand.cs
test/ScriptCs.Core.Tests/ReplCommands/AliasCommandTests.cs
test/ScriptCs.Core.Tests/ReplTests.cs
test/ScriptCs.Core.Tests/ScriptExecutorTests.cs
test/ScriptCsMoqCustomization.cs

re #909
to avoid breaking ConfigR with 0.14

revert breaking changes to ScriptExecutor in 909

---

src/ScriptCs.Core/ReplCommands/HelpCommand.cs
test/ScriptCs.Core.Tests/ReplCommands/HelpCommandTests.cs
test/ScriptCs.Core.Tests/ScriptCs.Core.Tests.csproj

Properly display REPL help after aliasing

---

src/ScriptCs.Core/ReplCommands/UsingsCommand.cs

include script pack namespaces in :usings

---

test/ScriptCs.Core.Tests/ScriptLibraryComposerTests.cs

missed in https://github.com/scriptcs/scriptcs/pull/986

change ScriptLibraryComposer test to ensure warn log level

---

build/ScriptCs.Version.props
src/ScriptCs.Engine.Mono/app.config
src/ScriptCs.Hosting/ScriptCs.Hosting.csproj
src/ScriptCs.Hosting/packages.config
test/ScriptCs.Core.Tests/ScriptCs.Core.Tests.csproj
test/ScriptCs.Core.Tests/packages.config
test/ScriptCs.Hosting.Tests/ScriptCs.Hosting.Tests.csproj
test/ScriptCs.Hosting.Tests/packages.config

This PR applies the changes made in c5048547cf70fc07dd13a72745d3f4d492260386 and 115f2e6afdbcc3ea354ab7cec412ae44d66c3611 (introduced to the dev branch in #1019) directly to the master branch for a hotfix release.

Hotfix NuGet.Core package reference

---

src/ScriptCs.Core/ScriptExecutor.cs

For now I made only changes to add/remove references and left the namespaces alone. This resolves #1036

made the references add/remove methods virtual #1036

---

src/ScriptCs.Core/Extensions/TypeExtensions.cs
src/ScriptCs.Hosting/ScriptServicesBuilder.cs
test/ScriptCs.Core.Tests/ReplCommands/ScriptPacksCommandTests.cs
test/ScriptCs.Core.Tests/ReplTests.cs
test/ScriptCs.Core.Tests/ScriptExecutorTests.cs

Corrected StyleCop warning messages.

StyleCop Cleanup

---

src/ScriptCs.Engine.Mono/MonoHost.cs
src/ScriptCs.Engine.Mono/ScriptCs.Engine.Mono.csproj
src/ScriptCs.Engine.Mono/Segmenter/Analyser/CodeAnalyzer.cs
src/ScriptCs.Engine.Mono/packages.config
test/ScriptCs.Engine.Mono.Tests/ScriptCs.Engine.Mono.Tests.csproj
test/ScriptCs.Engine.Mono.Tests/packages.config

Mono.CSharp -> 4.0.0
NRefactory -> 5.5.1

updated Mono.CSharp and NRefactory

---

src/ScriptCs.Engine.Mono/Segmenter/Lexer/ScriptLexer.cs
src/ScriptCs.Engine.Mono/Segmenter/Lexer/Token.cs
src/ScriptCs.Engine.Mono/Segmenter/Parser/RegionParser.cs
test/ScriptCs.Engine.Mono.Tests/Segmenter/RegionParserTests.cs

Fix 'else if' bug for mono #1060

---

src/ScriptCs.Contracts/ScriptCs.Contracts.csproj
src/ScriptCs.Core/ScriptCs.Core.csproj
src/ScriptCs.Engine.Mono/ScriptCs.Engine.Mono.csproj
src/ScriptCs.Engine.Roslyn/ScriptCs.Engine.Roslyn.csproj
src/ScriptCs.Hosting/ScriptCs.Hosting.csproj
src/ScriptCs/ScriptCs.csproj
test/ScriptCs.Core.Tests/ScriptCs.Core.Tests.csproj
test/ScriptCs.Engine.Mono.Tests/ScriptCs.Engine.Mono.Tests.csproj
test/ScriptCs.Engine.Roslyn.Tests/ScriptCs.Engine.Roslyn.Tests.csproj
test/ScriptCs.Hosting.Tests/ScriptCs.Hosting.Tests.csproj
test/ScriptCs.Tests.Acceptance/ScriptCs.Tests.Acceptance.csproj
test/ScriptCs.Tests/ScriptCs.Tests.csproj

Just an automated change using https://github.com/khellang/LangVersionFixer

Make sure we don't use C# 6 (yet)

---

src/ScriptCs/Command/ExecuteScriptCommand.cs

This is a (dirty) fix for #1086. This might be a temporary solution until some further refactoring can be done.

Hotfix for script-local cache folder

---

build/ScriptCs.Version.props

bump to version 0.16.0

---

README.md

Just a small readme update. It looks like the wiki has already been updated.

Updated README to reflect change from packages to scriptcs_packages

---

src/ScriptCs.Core/ScriptExecutor.cs
src/ScriptCs.Engine.Common/CommonScriptEngine.cs
test/ScriptCs.Core.Tests/ReplTests.cs
test/ScriptCs.Tests.Acceptance/ScriptExecution.cs

Add support for dynamic. 

---

src/ScriptCs/Command/InstallCommand.cs

fix failed install output

---

src/ScriptCs.Contracts/IConsole.cs
src/ScriptCs.Core/ReplCommands/ExitCommand.cs
src/ScriptCs.Hosting/FileConsole.cs
src/ScriptCs.Hosting/ScriptConsole.cs
src/ScriptCs.Hosting/ScriptCs.Hosting.csproj
src/ScriptCs.Hosting/getline.cs
src/ScriptCs/Command/ExecuteReplCommand.cs
test/ScriptCs.Core.Tests/ReplCommands/ExitCommandTests.cs
test/ScriptCs.Tests/ExecuteReplCommandTests.cs

This provides command line editing, history, and reverse history
search using the Emacs keybindings, similar to bash.

Provide editing capabilities using Mono.Terminal.GetLine.

---

src/ScriptCs.Contracts/IScriptExecutor.cs
src/ScriptCs.Core/ScriptExecutor.cs

made Namespaces collection immutable and relevant methods virtual #1040

---

.travis.yml
build.sh

* Locks Travis mono build version to 4.2.3.
* Fixes cp command.

Fixes #1172 and #1173

---

build/Build.proj

Adding scriptcs NuGet package #1061

---

src/ScriptCs.Core/ScriptEnvironment.cs
src/ScriptCs.Core/ScriptHostFactory.cs

Cleaner, and also needed for #244

Refactoring ScriptEnvironment to use IScriptInfo directly

---

src/ScriptCs.Core/FrameworkUtils.cs
src/ScriptCs.Core/ScriptCs.Core.csproj
src/ScriptCs.Hosting/Package/NugetInstallationProvider.cs
src/ScriptCs.Hosting/Package/ScriptCsPackageManager.cs
src/ScriptCs.Hosting/ScriptCs.Hosting.csproj
src/ScriptCs/Command/InstallCommand.cs

Adding custom package manager to allow forcing framework target version
